# Wherever you see ${} means I stored that bit of sensitive information inside of a .env file as a best-practice, I recommend you do the same. You will also find CHANGE_ME, define your own values here. 

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - CHANGE_ME # - Your Network Name
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`${TRAEFIK_HOST_RULE}`)" # - Your Traefik Host Rule
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`${TRAEFIK_HOST_RULE}`)" # - Your Traefik Host Rule
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=${SERVICE}"
      - "traefik.http.services.portainer.loadbalancer.server.port=${SERVICE_PORT}"  # - Service Port
      - "traefik.docker.network=CHANGE_ME" # - Your Network Name

networks:
  CHANGE_ME: # - Your Network Name
    external: true

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${ADDR},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4 # - Storage Server IP Address
      device: ":${DEVICE_MOUNT}" # - NFS Mount Path
