### Store your sensitive information in a .env as a best-practice. 
## I personally store a ton of information in my .env as you can see below. 
services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
       - $NETWORK # - Your Network Name
    environment:
      TRUSTED_PROXIES: "$REVERSE_PROXY_IP" # - Your Reverse Proxy IP Address
    volumes:
      - nextcloud:/var/www/html
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`$INTERNAL_HOST`) || Host(`$EXTERNAL_HOST`)" # - Your Internal and External DNS
      - "traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect"
      - "traefik.http.routers.nextcloud-secure.entrypoints=https"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`$INTERNAL_HOST`) || Host(`$EXTERNAL_HOST`)" # - Your Internal and External DNS
      - "traefik.http.routers.nextcloud-secure.tls=true"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=$SERVICE_PORT" # - Service Port
      - "traefik.docker.network=$NETWORK" # - Your Network Name
 
networks:
  $NETWORK: # - Your Network Name
    external: true

volumes:
  nextcloud:
    driver: local
    driver_opts:
      type: nfs
      o: addr=XXX.XXX.XXX.XXX,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4 # - Storage Server IP Address
      device: ":/mnt/" # - NFS Mount Path
  apps:
    driver: local
    driver_opts:
      type: nfs
      o: addr=XXX.XXX.XXX.XXX,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4 # - Storage Server IP Address
      device: ":/mnt/" # - NFS Mount Path
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=XXX.XXX.XXX.XXX,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4 # - Storage Server IP Address
      device: ":/mnt/" # - NFS Mount Path
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=XXX.XXX.XXX.XXX,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4 # - Storage Server IP Address
      device: ":/mnt/" # - NFS Mount Path